In [1]:
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.utils import shuffle
import numpy as np
import pandas as pd

In [9]:
iris=datasets.load_iris()
X=iris.data
Y=iris.target

#Shuffle of Data 
X,Y = shuffle(X,Y)

In [10]:
#CSV
df = pd.read_csv('data.csv')
df = df.replace('?',np.nan)
df.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
  
scaler.fit(df.drop('heartDisease', axis = 1))
scaled_features = scaler.transform(df.drop('heartDisease', axis = 1))
  
df_feat = pd.DataFrame(scaled_features, columns = df.columns[:-1])
df_feat.head()

age       sex        cp  trestbps      chol       fbs   restecg  \
0  0.948726  0.686202 -2.251775  0.757525 -0.264900  2.394438  1.016684   
1  1.392002  0.686202  0.877985  1.611220  0.760415 -0.417635  1.016684   
2  1.392002  0.686202  0.877985 -0.665300 -0.342283 -0.417635  1.016684   
3 -1.932564  0.686202 -0.165268 -0.096170  0.063974 -0.417635 -0.996749   
4 -1.489288 -1.457296 -1.208521 -0.096170 -0.825922 -0.417635  1.016684   

    thalach     exang   oldpeak     slope        ca      thal  
0  0.017197 -0.696631  1.087338  2.274579 -0.724246  0.660258  
1 -1.821905  1.435481  0.397182  0.649113  2.425706 -0.882607  
2 -0.902354  1.435481  1.346147  0.649113  1.375722  1.174546  
3  1.637359 -0.696631  2.122573  2.274579 -0.724246 -0.882607  
4  0.980537 -0.696631  0.310912 -0.976352 -0.724246 -0.882607

In [4]:
model=KMeans(n_clusters=3,init='k-means++',max_iter=10,n_init=1,random_state=3425)

In [5]:
#Training of the model
model.fit(X)

# This is what KMeans thought (Prediction)
Y_Pred=model.labels_

In [6]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(Y,Y_Pred)
print(cm)

from sklearn.metrics import accuracy_score

print(accuracy_score(Y,Y_Pred))

[[32  0 18]
 [ 0 46  4]
 [ 0 50  0]]
0.52


In [7]:
#Defining EM Model
from sklearn.mixture import GaussianMixture
model2=GaussianMixture(n_components=3,random_state=3425)

#Training of the model
model2.fit(X)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
                means_init=None, n_components=3, n_init=1, precisions_init=None,
                random_state=3425, reg_covar=1e-06, tol=0.001, verbose=0,
                verbose_interval=10, warm_start=False, weights_init=None)

In [8]:
#Predicting classes for our data
Y_predict2= model2.predict(X)

#Accuracy of EM Model
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(Y,Y_predict2)
print(cm)

from sklearn.metrics import accuracy_score

print(accuracy_score(Y,Y_predict2))

[[38  0 12]
 [ 0 50  0]
 [ 0 50  0]]
0.5866666666666667
